import {
  LayoutDashboard,
  ShoppingCart,
  Package,
  Users,
  Wallet,
  BarChart3,
  FileText,
  Shield,
  CreditCard,
  Factory,
  Truck,
  Settings,
  Plug,
  Undo2,
  PackagePlus,
  Warehouse,
  FolderTree,
  Layers,
  XCircle,
  Activity,
  Printer,
  CheckCircle2,
  RefreshCw,
  ClipboardList,
  AlertCircle,
  PieChart,
  PackageCheck,
  Headset,
  RefreshCcw,
  AlertTriangle,
  Store,
  CheckSquare,
  Clock,
  Landmark,
  DollarSign,
  Boxes,
  MessageSquare,
  Ticket,
  Rocket,
  GraduationCap,
  Bot,
  Tags,
  UserRoundSearch,
  Megaphone,
  ArrowLeftRight,
  Globe,
} from "lucide-react";
import { FaBugs, FaMessage, FaUserTie } from "react-icons/fa6";
import { FaBolt, FaBug, FaChartPie, FaClock, FaListAlt, FaPlus, FaRegFileAlt, FaWhatsapp } from "react-icons/fa";

export const testEmails = ["fohas49541@luckfeed.com", "am2592379@gmail.com", "admin@gmail.com"];
export function getSidebarMenuItems({ isDirectShippingEnabled = false } = {}) {
  return [
    {
      icon: Rocket,
      labelKey: "getting_started",
      href: "/getting-started",
      roles: ["ADMIN"],
    },
    {
      icon: LayoutDashboard,
      labelKey: "dashboard",
      href: "/dashboard",
      permission: "dashboard.read",
    },
    {
      icon: Headset,
      labelKey: "callCenter",
      href: "/call-center",
      permission: "orders.distribution",
      gettingStartedKey: "call_center",
      gettingStartedType: "sidebar_item",
    },
    {
      icon: Activity,
      labelKey: "employee-performance",
      href: "/orders/employee-orders/dashboard",
      permission: "orders.confirm-incoming",
      roles: ["CALL CENTER"],
      notRoles: ["ADMIN", "SUPER_ADMIN"],
    },
    {
      icon: PackageCheck,
      labelKey: "orders-assign-to-you",
      href: "/orders/employee-orders",
      permission: "orders.confirm-incoming",
      roles: ["CALL CENTER"],
      notRoles: ["ADMIN", "SUPER_ADMIN"],
    },
    {
      icon: ShoppingCart,
      labelKey: "orders",
      href: "/orders",
      permission: "orders.read",
      children: [
        {
          icon: Package,
          labelKey: "orders",
          permission: "orders.read",
          href: "/orders?tab=orders",
          gettingStartedKey: "sidebar_item_orders",
          gettingStartedType: "sidebar_item",
        },
        {
          icon: Undo2,
          labelKey: "orderReplacement",
          href: "/orders?tab=replacement",
          permission: "orders.readReplace",
        },
        {
          icon: XCircle,
          labelKey: "warehouseRejected",
          href: "/orders?tab=rejected",
          permission: "orders.read",
        },
        {
          icon: RefreshCcw,
          labelKey: "pendingOrders",
          href: "/orders?tab=failedOrders",
          permission: "orders.restoreFailed",
        },
        {
          icon: Truck,
          labelKey: "shippedOrders",
          href: "/orders?tab=shippedOrders",
          permission: "orders.read",
        },
        {
          icon: XCircle,
          labelKey: "cancelCauses",
          href: "/cancel-causes",
          permission: "cancel-causes.read",
        },
        {
          icon: Tags,
          labelKey: "tags",
          href: "/tags",
          notRoles: ["CALL CENTER"],
          permission: "tags.read",
        },
      ],
    },
    {
      icon: Users,
      labelKey: "customers",
      href: "/customers",
      children: [
        {
          icon: Users,
          labelKey: "customers",
          href: "/customers",
          permission: "customer.read",
        },
        {
          icon: Tags,
          labelKey: "customersTags",
          href: "/customers/tags",
          notRoles: ["CALL CENTER"],
          permission: "tags.read",
        },
        {
          icon: UserRoundSearch,
          labelKey: "customersSegments",
          href: "/customers/segments",
          permission: "client-segments.read",
          allowedEmails: ["fohas49541@luckfeed.com", "am2592379@gmail.com", "admin@gmail.com"],
        },
      ],
    },
    isDirectShippingEnabled
      ? {
        icon: Truck,
        labelKey: "warehouseDistribution",
        href: "/warehouse?tab=distribution",
        children: [
          {
            icon: Truck,
            labelKey: "warehouseDistribution",
            href: "/warehouse?tab=distribution",
            permission: "orders.distribution",
          },
          {
            icon: ClipboardList,
            labelKey: "warehouseLogs",
            href: "/warehouse?tab=logs",
            permission: "warehouses.read",
          },
        ],
      }
      : {
        icon: Warehouse,
        labelKey: "manageWarehouse",
        href: "/warehouse",
        children: [
          {
            icon: Truck,
            labelKey: "warehouseDistribution",
            href: "/warehouse?tab=distribution",
            permission: "orders.distribution",
          },
          {
            icon: Printer,
            labelKey: "warehousePrint",
            href: "/warehouse?tab=print",
            permission: "warehouses.read",
          },
          {
            icon: Package,
            labelKey: "warehousePreparation",
            href: "/warehouse?tab=preparation",
            permission: "warehouses.scan-preparation",
          },
          {
            icon: CheckCircle2,
            labelKey: "warehouseOutgoing",
            href: "/warehouse?tab=outgoing",
            permission: "warehouses.scan-shipping",
          },
          {
            icon: RefreshCw,
            labelKey: "warehouseReturns",
            href: "/warehouse?tab=returns",
            permission: "warehouses.read",
          },
          {
            icon: ClipboardList,
            labelKey: "warehouseLogs",
            href: "/warehouse?tab=logs",
            permission: "warehouses.read",
          },
        ],
      },
    {
      icon: Package,
      labelKey: "products",
      href: "/products",
      children: [
        { icon: Package, labelKey: "products", permission: "products.read", href: "/products" },
        { icon: PackagePlus, labelKey: "newProduct", permission: "products.create", href: "/products/new", gettingStartedKey: "sidebar_item_products_add", gettingStartedType: "sidebar_item" },
        { icon: Layers, labelKey: "newBundle", permission: "products.create", href: "/bundles/new", gettingStartedKey: "products.add_bundle", gettingStartedType: "sidebar_item" },
        { icon: Package, labelKey: "categories", permission: "categories.read", href: "/products/categories" },
        { icon: Boxes, labelKey: "warehousesManagement", permission: "warehouses.read", href: "/warehouses-management", gettingStartedKey: "products.warehouses_management", gettingStartedType: "sidebar_item_products_warehouse" },
      ],
    },
    {
      icon: Plug,
      labelKey: "synchronization",
      href: "/shipping-companies",
      children: [
        {
          icon: Truck,
          labelKey: "shippingCompanies",
          permission: "shipping-companies.read",
          href: "/shipping-companies",
          gettingStartedKey: "integrations.shipping_companies",
          gettingStartedType: "sidebar_item",
        },
        {
          icon: ArrowLeftRight,
          labelKey: "shippingAssigning",
          permission: "shipping-assigning.read",
          href: "/shipping-assigning",
          allowedEmails: ["fohas49541@luckfeed.com", "am2592379@gmail.com", "admin@gmail.com"],
        },
        {
          icon: Store,
          labelKey: "stores",
          permission: "stores.read",
          href: "/store-integration",
          gettingStartedKey: "integrations.stores",
          gettingStartedType: "sidebar_item",
        },
        {
          icon: AlertTriangle,
          labelKey: "syncFailures",
          permission: "stores.read",
          href: "/store-integration/sync-failures",
        },
      ],
    },
    {
      icon: FaWhatsapp,
      labelKey: "whatsapp",
      href: "/whatsapp",
      children: [
        {
          labelKey: "overview",
          href: "/whatsapp",
          icon: FaChartPie,
          permission: "whatsapp.read",
        },
        {
          labelKey: "whatsAppAccounts",
          href: "/whatsapp/accounts",
          icon: FaWhatsapp,
          gettingStartedKey: "whatsapp.accounts",
          gettingStartedType: "sidebar_item",
          permission: "whatsapp.manage",
        },
        {
          labelKey: "templates",
          href: "/whatsapp/templates",
          icon: FaRegFileAlt,
          permission: "whatsapp.templates.read",
        },
        {
          labelKey: "chats",
          href: "/whatsapp/chats",
          icon: FaMessage,
          permission: "conversation.read",
        },
        {
          labelKey: "upsell",
          href: "/upsells",
          icon: FaChartPie,
          permission: "upsells.read",
        },
      ],
    },
    {
      icon: Megaphone,
      labelKey: "campaigns",
      href: "/campaigns",
      permission: "campaigns.read",
      allowedEmails: ["fohas49541@luckfeed.com", "am2592379@gmail.com", "admin@gmail.com"],
    },
    {
      icon: MessageSquare,
      labelKey: "sms",
      href: "/sms/providers",
      children: [
        {
          icon: Plug,
          labelKey: "smsProviders",
          href: "/sms/providers",
          permission: "sms.providers.read",
        },
        {
          icon: Users,
          labelKey: "smsSenders",
          href: "/sms/senders",
          permission: "sms.senders.read",
        },
        {
          icon: FileText,
          labelKey: "smsLogs",
          href: "/sms/logs",
          permission: "sms.logs.read",
        },
      ],
    },
    {
      icon: FaBolt,
      labelKey: "automations",
      href: "/automations",
      children: [
        {
          labelKey: "automationsPaths",
          href: "/automations",
          icon: FaBolt,
          gettingStartedKey: "automation.automations",
          gettingStartedType: "sidebar_item",
          permission: "automation.read",
        },
        {
          labelKey: "automationLogs",
          href: "/automations/logs",
          icon: FaListAlt,
          permission: "automation.read",
        },
        {
          labelKey: "runningAutomations",
          href: "/automations/running",
          icon: FaClock,
          permission: "automation.read",
        },
      ],
    },
    {
      icon: Bot,
      labelKey: "ai",
      href: "/ai",
      permission: "ai.chat",
      allowedEmails: ["fohas49541@luckfeed.com", "am2592379@gmail.com", "admin@gmail.com"],
    },
    {
      icon: BarChart3,
      labelKey: "reports",
      href: "/reports",
      children: [
        {
          icon: PieChart,
          labelKey: "order-analysis",
          href: "/reports/order-analysis",
          permission: "dashboard.read",
        },
        {
          icon: Activity,
          labelKey: "employee-performance-analysis",
          href: "/reports/employee-performance-analysis",
          permission: "dashboard.read",
        },
        {
          icon: Truck,
          labelKey: "shippingReport",
          href: "/reports/shipping",
          permission: "dashboard.read",
        },
        {
          icon: XCircle,
          labelKey: "cancelCausesStatistics",
          href: "/reports/cancel-causes-analysis",
          permission: "cancel-causes.statistics",
        },
      ],
    },
    {
      icon: Wallet,
      labelKey: "accounts",
      href: "/collections",
      children: [
        {
          icon: Wallet,
          labelKey: "accounts",
          href: "/accounts?tab=overview",
          permission: "accounting.read",
        },
        {
          icon: Landmark,
          labelKey: "safes",
          href: "/accounts?tab=safes",
          gettingStartedKey: "accounts.safes",
          gettingStartedType: "sidebar_item",
          permission: "safes.read",
        },
        {
          icon: CheckSquare,
          labelKey: "collectedOrders",
          href: "/orders/collections?tab=collected",
          permission: "orders-collect.read",
        },
        {
          icon: Clock,
          labelKey: "uncollectedOrders",
          href: "/orders/collections?tab=not_collected",
          permission: "orders-collect.read",
        },
      ],
    },
    {
      icon: Factory,
      labelKey: "administration",
      href: "/suppliers",
      children: [
        {
          icon: Factory,
          labelKey: "suppliers",
          permission: "suppliers.read",
          href: "/suppliers",
          gettingStartedKey: "purchases.suppliers",
          gettingStartedType: "sidebar_item",
        },
        {
          icon: FileText,
          labelKey: "purchases",
          permission: "purchases.read",
          href: "/purchases",
          gettingStartedKey: "purchases.purchases",
          gettingStartedType: "sidebar_item",
        },
        { icon: PackagePlus, labelKey: "newPurchase", permission: "purchases.create", href: "/purchases/new" },
        { icon: Undo2, labelKey: "purchasesReturn", permission: "purchase_returns.read", href: "/purchases/return" },
      ],
    },
    {
      icon: DollarSign,
      labelKey: "finance",
      href: "/wallet",
      children: [
        {
          icon: Wallet,
          labelKey: "wallet",
          roles: ["ADMIN"],
          permission: "wallet.read",
          href: "/wallet",
        },
        {
          icon: CreditCard,
          labelKey: "plans",
          roles: ["ADMIN"],
          permission: "plans.read",
          href: "/plans",
        },
      ],
    },
    {
      icon: Users,
      labelKey: "team",
      href: "/employees",
      children: [
        {
          icon: FaUserTie,
          labelKey: "employees",
          permission: "users.read",
          href: "/employees",
          gettingStartedKey: "teams.add_employees",
          gettingStartedType: "sidebar_item",
        },
        {
          icon: Shield,
          labelKey: "roles",
          permission: "roles.read",
          href: "/roles",
          gettingStartedKey: "teams.roles_permissions",
          gettingStartedType: "sidebar_item",
        },
      ],
    },
    {
      icon: FaBug,
      labelKey: "issuesAndStatuses",
      href: "/issues",
      children: [
        {
          icon: AlertCircle,
          labelKey: "issuesAndStatuses",
          href: "/issues",
          permission: "issues.read",
        },
        {
          icon: FolderTree,
          labelKey: "manageCauses",
          href: "/issues/causes",
          permission: "issues.causes.update",
        },
      ],
    },
    {
      icon: Ticket,
      labelKey: "supportTickets",
      href: "/support-tickets",
      permission: "support_tickets.read",
    },
    {
      icon: Settings,
      labelKey: "settings",
      href: "/settings",
      permission: "admin-settings.read",
    },
    {
      icon: Users,
      labelKey: "users",
      href: "/dashboard/users",
      roles: ["SUPER_ADMIN"],
    },
    {
      icon: GraduationCap,
      labelKey: "gettingStartedStatistics",
      href: "/dashboard/getting-started",
      roles: ["SUPER_ADMIN"],
    },
    {
      icon: Shield,
      labelKey: "roles",
      href: "/dashboard/roles",
      roles: ["SUPER_ADMIN"],
    },
    {
      icon: CreditCard,
      labelKey: "plans",
      href: "/dashboard/plans",
      roles: ["SUPER_ADMIN"],
    },
    {
      icon: FileText,
      labelKey: "orders",
      href: "/dashboard/orders",
      roles: ["SUPER_ADMIN"],
    },
    {
      icon: Globe,
      labelKey: "platformSettings",
      href: "/dashboard/settings",
      roles: ["SUPER_ADMIN"],
    },
    {
      icon: FaWhatsapp,
      labelKey: "whatsapp",
      href: "/dashboard/whatsapp",
      roles: ["SUPER_ADMIN"],
      children: [
        {
          labelKey: "templates",
          href: "/dashboard/whatsapp/templates",
          icon: FaRegFileAlt,
          roles: ["SUPER_ADMIN"],
        },
        {
          labelKey: "addTemplate",
          href: "/dashboard/whatsapp/templates/add",
          icon: FaPlus,
          roles: ["SUPER_ADMIN"],
        },
      ],
    },
    {
      icon: Users,
      labelKey: "customers",
      href: "/dashboard/customers",
      roles: ["SUPER_ADMIN"],
      children: [
        {
          icon: UserRoundSearch,
          labelKey: "customersSegmentsTemplate",
          href: "/dashboard/customers/segments",
          roles: ["SUPER_ADMIN"],
        },
      ],
    },
    {
      icon: FaBugs,
      labelKey: "systemErrors",
      href: "/dashboard/errors",
      roles: ["SUPER_ADMIN"],
    },
    {
      icon: Headset,
      labelKey: "supportTicketsAdmin",
      href: "/dashboard/support-tickets",
      roles: ["SUPER_ADMIN"],
    },
  ];
}
